 
apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: application
  lifecycle: production
  owner: user:guest
metadata:
  name: ${{ values.artifactId }}
  labels:
    app.kubernetes.io/name: ${{ values.artifactId }}
    app.kubernetes.io/version: ${{ values.version }}
    app.quarkus.io/version: 3.15.0
  annotations:
    backstage.io/source-location: url:https://github.com/iocanel/${{ values.artifactId }}
  tags:
  - java
  - quarkus
